### ISSUE TITLE
Ability to rename the store

### ISSUE THREAD

**Issue by robclancy** [toranb/ember-cli-simple-store#23]
I mean what you register it as in https://github.com/toranb/ember-cli-simple-store/blob/master/addon/initializers/ember-cli-simple-store.js#L5.

Basically we have moved from `ember-data` to `ember-model` and they both suffer from the same issues of stability, too much magic and not giving the developer the power to do things the way they want with their API. But moving from one to the other is a big job and we want to move more towards your approach as it gives developers all the power in how things work. However you share the `store` name with `ember-model` so this becomes difficult, we can't spend all the time moving everything right away. Instead we want to migrate over time as we realize our use cases and how we want to do everything. For now I think we will just fork this and name it `storage`.

**Comment by toranb** [comment]
I think the best case scenario for this would be to pull the initializer (that gives it the name "store") allowing others to create any name/inject it how they want. The downside is this would be a big breaking change and I'd need to wait for the v4.0 release.

https://github.com/toranb/ember-cli-simple-store/blob/master/addon/initializers/ember-cli-simple-store.js#L6-L7

If you see this as a short term change to help you refactor I'd say we skip the "configure name" feature unless I start hearing from a few others that "store" isn't a good name/ or they want to configure it like you mention.

I've been planning to blog/speak more about how to use this addon and keep "rich relationships between models" (plus dirty tracking). Are you using / or in need of one-to-many, m2m relationships and dirty tracking as the clients I work for? Also, do you do any embedded POST/ or a mix of some embedded payloads and some not? Are you using a JSON API backend/ if not what is your server side (if you can say)?

Sorry for the questions but I honestly thought I was the _only_ person using this library until 30 days ago :)

**Comment by williamsbdev** [comment]
Since the initializer is included in the app:

https://github.com/toranb/ember-cli-simple-store/blob/master/app/initializers/ember-cli-simple-store.js

You will have the ability to override in the app where you include this addon. You can simple create a file named `ember-cli-simple-store.js` in your `initializers` directory. You can do something like this to get your app having the `store` named as `storage`.

``` js
// your-app/initializers/ember-cli-simple-store.js

import Store from 'ember-cli-simple-store/store';

export default function() {
    var application = arguments[1] || arguments[0];
    application.register('storage:main', Store);
    application.inject('controller', 'storage', 'storage:main');
    application.inject('route', 'storage', 'storage:main');
}
```

@robclancy please try this out and let me know if this works for you.

**Comment by robclancy** [comment]
@toranb yes JSON for this but no to relationships, I find them as overrated on the client side. We do have relationships but simply handle them manually with a manual call to the repository passing in the ID needed. Code can explain better than me...

``` js
export default Ember.Object.extend(PromiseMixin, {
  findById(id) {
    var store = this.get('storage');
    return this.xhr('/api/organizations/' + id).then(record => {
      return store.push('organization', record);
    });
  },
  projects(id) {
    var store = this.get('storage');
    return this.xhr('/api/organizations/' + id + '/projects').then(response => {
      response.data.forEach(record => {
        store.push('project-temp', record);
      });

      return store.find('project-temp');
    });
  },
});
```

Then in my `organization` model I have a `loadProjects` method I can call when needed. Works similar to a relationship but instead is explicit so you know exactly what is going on and can use your API however you like.

I can't think of a use case where I will need dirty tracking. I doubt I will modify items in place and instead have a copy of them... not sure yet though as this is early days. I just want to be able to do anything I like without having to hack things which is what the libraries made by you and @williamsbdev allow me to do. I was initially just going to use normal es6 classes but this seems a lot better to keep things working with computed properties.

@williamsbdev yeah I figured I was missing something like this but wasn't sure and ember is pretty scarce on some of it's documentation. So just quickly forked to prototype everything. I will make those changes lately and get back to you.

**Comment by williamsbdev** [comment]
Thanks for the feedback. I will start a blog post about
extending/overriding addons and look into add documentation to
ember/ember-cli for the extensions I'm talking about. If you have any
issues, hit me up and I can help out or pair if needed.

**Comment by williamsbdev** [comment]
@robclancy, I just put together a [commit](https://github.com/williamsbdev/ember-cli-simple-store-as-storage/commit/282e58ba9a1668971836b8496cb35ed3451c4e7c) that shows `ember-data` and `ember-cli-simple-store` side by side. I renamed the `store` from `ember-cli-simple-store` -> `storage`.

Like I said, today I will read through the ember-cli documentation and see if I can make it more clear how to override features from an addon. I will also throw up a blog post and link to it via this issue.

**Comment by bmac** [comment]
@williamsbdev. If you are thinking of changing the name used to register the store I'd recommend you take the time now to think about supporting registering it as a `service` to allow users to use the normal `Ember.inject.service` methods to access the store in their components (or anywhere). 

If you decide down the road that you'd rather register it as a service, trying to get multiple registered names to refer to the same object is tricky to get right, especially if you allow users to define a custom `store`.

**Comment by williamsbdev** [comment]
@bmac I was not planning or considering changing the name of the store. The commit I referenced above only those a way that this user would be able to slowly switch away from ember-data if they so choose. Since both ember-data and ember-cli-simple-store want to be referenced as store, store -> storage, is a temporary stop gap.

I am curious if ember-data is going to move towards the `service` model? If so, this may be something we should consider.

**Comment by williamsbdev** [comment]
@bmac so after looking at ember-data, I noticed that the `store` is actually registered as a service and then injected into the appropriate objects, but also allows for injection.

Thanks for the suggestion. This is something that @toranb and I will have to discuss and explore.

**Comment by williamsbdev** [comment]
@robclancy I could not find a good location for the this [post's material](http://williamsbdev.com/posts/overriding-ember-addons/) in the ember-cli documentation. I also referenced a [SO question/answer](http://stackoverflow.com/questions/29634920/how-to-override-default-functionality-in-ember-addons) in my post. I hope this is helpful.

**Comment by robclancy** [comment]
I have done what you suggested and it is all working fine. Things feel much better using these libraries compared to ember-data or ember-model.

**Comment by toranb** [comment]
@bmac I'll work with @williamsbdev to provide a service/or configurable injection option this week. Thanks for dropping in to provide some info about Ember.inject.service

**Comment by toranb** [comment]
@williamsbdev thanks for helping @robclancy with this -always looking for the best talent in the biz :)
