### ISSUE TITLE
Performance issues pushing with a large number of records in the store

### ISSUE THREAD

**Issue by toranb** [toranb/ember-cli-simple-store#25]
In issue #22 @matthewnessworthy mentioned

```
I'm running into a separate unrelated issue at the moment relating to adding items to the store.
When there are a few thousand records in the store the time to push a record increases significantly,
from ±1ms with a few records up to 11sec (per push) when there are about 4000 records.
I've tried to mitigate this by wrapping bulk data pushes with store.beginPropertyChanges();
and store.endPropertyChanges(); which makes a huge difference, but I'm still running into
issues when the store gets larger.
```

He then put together a sample project to show this off. I wanted to start a new conversation here so we can stay focused on the problem he found/ work through a solution with the appropriate history.

https://github.com/matthewnessworthy/ember-cli-simple-store-perf

**Comment by toranb** [comment]
@matthewnessworthy could you clarify a few things for me when you get time? Is the core problem that doing a "bulk insert" is slow (as the size of the record set grows)? Or is the core issue that inserting a single record is slow (after the store has 4000+ records in it)?

I ask because in your example, if I push 3000 records in a "single push" is still speedy (just under 1 second). Originally when I got your message I assumed this situation was broken but now I'm beginning to think your original problem might have been the "push many"

Thanks for the input -just trying to better understand the problem you had/ need help with.

**Comment by matthewnessworthy** [comment]
@toranb It's still single pushes that are affected. Perf varies depending on the number of computed properties depending on the store find results (like the `belongs_to` example you gave), where each record has a computed property referencing the same type of model (think recursive parent-child).

I'm getting responses of greater than 5 seconds when pushing blocks of 100 records on a store with 2000+ records, and the total time increases by about 50-250ms for each 100 records added after that

**Comment by toranb** [comment]
I've reached out to a member of the core team on this for some paid perf consulting. I honestly don't know how to tune the ArrayProxy myself but understand the need. I'll let you know what I find out in the coming days/weeks (sorry for the lack of knowledge on this @matthewnessworthy )

**Comment by toranb** [comment]
Sorry for the huge holiday sized delay on this one - I finally got some time w/ one of the ember core team and it was well worth the wait! In fact I threw together a quick spike just a few minutes ago to show what we discussed (and it does indeed speed things up -big time).

https://github.com/toranb/ember-cli-simple-store/commit/e475e4a3b82b9eb6498524e6dde95406cde635e5

The biggest challenge is that this work isn't trivial (level of effort anyway) and I almost need to have it sponsored (to ensure I have enough time/ and enough of a code base to test it to ensure we don't have any funky regressions/etc)

Can you look the commit above over when you get a few to see if it sounds logical? The basic idea is that we can't re-computed the ArrayProxy (when you filter using find) right away -instead we need to capture each filter (by type) and schedule a "set" using the run loop. In the end it seems to give the result you'd expect but I have to imagine the complete (and bug free) refactor will require some time.

**Comment by matthewnessworthy** [comment]
No worries, end of the year always end up being more hectic than expected.

The main performance pain points are:
- adding a large number of records without wrapping them in a `beginPropertyChanges`/`endPropertyChanges`
- adding 1 or more records into a store that already contains a large number or records (compare perf adding a single record to an empty store compared to adding that same record with a store of 5000)

Regarding the commit https://github.com/toranb/ember-cli-simple-store/commit/e475e4a3b82b9eb6498524e6dde95406cde635e5, it can/should work, but how to you intend to schedule a filter recompute when records change or when existing records are added to the store (`Store.push` with a matching id, which doesn't call `buildRecord`)?

**Comment by toranb** [comment]
Great question - I have a few of my own that I'd like to drive out using a large code base. Below is a list of the requirements I have for the rewrite (this looks like the setup for v4.0.0)

0) improve performance for pushing models into the store
1) store.push for new records
2) store.push for existing records
3) related filters still recompute correctly*
4) keep all the functionality of the store as-is (no regressions)

*often in complex apps you have a relationship like this (example: one-to-many)

``` js
var User = Model.extend({
    role: Ember.computed.alias('belongs_to.firstObject'),
    belongs_to: Ember.computed(function() {
        let user_id = this.get('id');
        let store = this.get('store');
        let filter = function(role) {
            let users = role.get('users');
            return Ember.$.inArray(user_id, users) > -1;
        };
        return store.find('role', filter, ['users']);
    })
});
```

Here is a simple unit test to show the relationship above (and how the filter looks from the data structure view point). Notice role has an array with "users" //more on this below

``` js
test('role should return associated model or undefined', function(assert) {
    let user = store.push('user', {id: 1});
    store.push('role', {id: 2, name: 'Admin', users: [1]});
    let role = user.get('role');
    assert.equal(role.get('id'), 2);
    role.set('users', []);
    role = user.get('role');
    assert.equal(role, undefined);
});
```

The trick w/ this relationship (common in our apps) is that the find in user should recompute when the array on any role is updated. Today the spike I show above _should_ in theory do this because the filter is on "role" and if users (the array on any role model) is changed we should update the ArrayProxy (at the end of the run-loop). I call this feature out because it's very critical to any app that grows beyond hello world (and if this rewrite is to be a success I'll need to focus on this first).

Any other questions or bullet points let me know. I'd like to keep this issue open until we truly land a v4.0.0-beta.1 or something (and I'd love your help identifying issues along the way).

**Comment by toranb** [comment]
**Update**

The reason that relationship I showed above is _tricky_ is that we need to recompute when the array "users" on role is updated ... but we don't usually "push" to do that update. We normally just do a set (in the model like you see below). This would require some thought because the "quick fix" is to require a push for all setter changes like this (something I haven't even done myself) or some other hack that I haven't yet discovered. Any thoughts on this specifically?

``` js
var User = Model.extend({
    change_role: function(new_role_id) {
        let user_id = this.get('id');
        let store = this.get('store');
        let new_role = store.find('role', new_role_id);
        let new_role_users = new_role.get('users') || [];
        new_role.set('users', new_role_users.concat(user_id));
        //the set above won't force a re-compute :(
    }
});
```

**a thought occurs...**

In the above example the find returns an ObjectProxy (from simple store). I could wrap the "set" method directly -allowing me to schedule a filter update (followed by a super to let ember do it's magic)

**Comment by toranb** [comment]
I'm working to complete the v4.0.0 release this week and it will include the much desired/needed perf update you uncovered here @matthewnessworthy 

I'm using my largest installed app to upgrade this privately first (so I can feel the pain/ work through any issues). I plan to release a version for you to play with some time Wed or Thursday at the latest.

I'll be sure to include a note in the README about upgrading from v3 to v4. At this time the changes are as follows 

1) any time you do a push it will require an ember.run
2) any time you update a filtered on property you need to use push instead of a simple "set"
3) find w/ filter (function) will be simplified -no longer will you need to say what computed keys to break on

Any questions or concerns let me know! I'll update this issue as I learn more about the upgrade process

**Comment by toranb** [comment]
After a solid days work I've got the first iteration up in a commit worth looking at. I tested it heavily against your perf app and found I'm able to push 100 records at a time (w/ 4K in the store) and it takes between 126-148ms

https://github.com/toranb/ember-cli-simple-store/commit/69fe0ba936fa00859778d4c94572878c88a4f1ef

I'll take a run at upgrading a real application tomorrow and document the process here

![fastperfsimplestore](https://cloud.githubusercontent.com/assets/147411/12027232/c5db9358-ad88-11e5-913a-cb443256ec1f.gif)

**Comment by toranb** [comment]
@matthewnessworthy day 2 and so far it's looking good. I did a patch (beta.2) release this morning when I found another bug. The biggest pain point is upgrading the app itself to avoid using "set" all over.

Depending on the size of your app (and the amount of filters you've created) it might be a costly update (level of effort). I spent all day and made it through the most complex model we have (lots of m2m/one-to-many relationships). The good news is that I'm making progress w/out any real blockers to note.

**Comment by toranb** [comment]
@matthewnessworthy another quick update - I got our app completely up to date w/ no issues. The biggest lesson learned is that I should have created a base qunit test that just wrapped the inners w/ ember.run (would have saved me a ton of time). I plan to write up a short "guide" about what I learned but honestly the bulk was "update your unit tests as they don't wrap store.push w/ ember.run"

All the production code was already wrapped with ember.run. For example, beforeModel (ember managed), any closure action in ember 2.3+ (like onclick/ onchange) and all my ajax work was already wrapped w/ a base xhr mixin I've been using.

https://github.com/toranb/ember-promise/blob/master/addon/mixins/promise.js#L12

I've got 2 concerns worth talking about before the v4.0.0 release (stable).

1) because each ArrayProxy is "saved" and pushed into a list of filters I'd like to think we could reuse them when another filter (for the same time) comes in w/ the same function. This would be another performance win long term because you'd only need to update each filter (per type) once instead of multiple times.

2) because each ArrayProxy has a reference in the store now ... how could the app unsubscribe (or remove it when it's not needed any longer)? It might be the case that over a full day this isn't a problem but I can't help but think "each registered filter now has a reference that may/ or may not be active"

Would you mind taking a run at the upgrade to beta-2 in the next week or so and see if you find anything I didn't? If you are able to update w/out issue and I can solve issue one (maybe two) above I think a legit v4.0.0 could be published in January.

**Comment by toranb** [comment]
Here is a quick hack for that qunit test I mentioned above (wraps the callback w/ ember.run for pure unit tests with a lot of store.push code)

``` js
import Ember from 'ember';
import {test as qunitTest} from 'qunit';
import {module} from 'qunit';

var test = function test() {
  for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; ++_key) {
    args[_key] = arguments[_key];
  }
  var callback;
  function wrapper() {
      let argz = arguments;
      Ember.run(function() {
          callback.apply(null, argz);
      });
  }
  callback = args.splice(1, 1, wrapper)[0];
  qunitTest.apply(null, args);
}

export { module, test };
```

**Comment by toranb** [comment]
@matthewnessworthy another update - had a chat w/ another run-loop expert and it looks like the queue (afterRender) may be a problem as it won't update filters (ArrayProxy) as you might expect. I'm planning to run this in sync or actions instead. I'll report back when I know more :)

**Comment by toranb** [comment]
@matthewnessworthy cut another release today for beta 3

Some discoveries from yesterday. 

1) I thought moving from afterRender to actions or sync would solve my "explicit run" problem but no
2) I could improve the calls to scheduleOnce further using ember.run.once in push/remove/clear
3) without an explicit action (regardless of queue) you won't flush relationships (inconsistent computed properties then plague you forever)
4) wrapping the scheduleOnce w/ ember.run.once did help in testing a bit -unit tests can now be less verbose _the commit below shows how I was able to cut out a ton of ember.runs from unit tests_

https://github.com/toranb/ember-cli-simple-store/commit/bc4e52f0f90bf72594ea9dc39b8739adc18c6a57

**Comment by toranb** [comment]
@matthewnessworthy I landed the reuse feature today but sadly it won't work for the simple filter (object literal syntax for find). I'm toying with the idea of leaving it (vs deprecation for example). The only issue is that w/ the fork now it's not consistent. I assume the caching is valuable enough to remove the more simplified syntax but I'd like to put more time into it before changing the API

If you get time to look it over I just cut beta 4

**Comment by toranb** [comment]
@matthewnessworthy disregard -beta.4 is a bad build (just found this trying to run it against the app I'm working on). Avoid it if you can :)

**Comment by toranb** [comment]
After some thought/discussion with someone on the ember-data core team it's clear what I attempted to do in beta.4 (that failed) was "reuse" any ArrayProxy that gets spun up. Instead the approach I'll recommend to people going forward is that you cache a reference to this in your service/or repository like classes and manage the "reuse" yourself.

The question about "memory usage over time" was less eventful. Some discussion has gone around about this and one RFC worth reading is shown below. It wasn't implemented but some good discussion came out of the issue regardless.

https://github.com/emberjs/rfcs/pull/23

The core problem is that the store holds on to each "filtered ArrayProxy" so the garbage collector is prevented from reclaiming any ArrayProxy created (for filtering purposes) ... meaning this introduces a legit memory leak.

I honestly need more time to solve this problem and I thought originally users of this api could call a special "unsubscribe" or "destroy" like action w/ a given ArrayProxy when a route transitions away/or a component is destroyed for example. The problem is that most people would either 1) forget about it or 2) hate the boiler plate required to manage this manually (and I personally don't like either option myself).

For now I've published a beta.5 which is nothing more than a revert of the code previously included in the beta.4 that failed. @matthewnessworthy if you get time to run at this w/ beta.3 or beta.5 I'd love your feedback on the performance / what you found during the upgrade process.

**Comment by matthewnessworthy** [comment]
Hey @toranb, I did a quick upgrade, and I was surprised at how straightforward it was. I haven't seen much in the way of breakage and things continue to work pretty much as expected.

I think part of the reason is because a lot of the stuff we are currently doing is, in one way or another, wrapped in run loops. Front your comments above I was expecting there to be quite a few broken sections, but honestly, everything is looking good.

On the performance side, the store is no longer the bottleneck. The performance is massively, especially when adding 1000's of records to an already partially populated store. Now most of the performance slowdowns I'm experiencing are rooted in rendering or other components.

Thanks for the great update!

**Comment by toranb** [comment]
@matthewnessworthy wow that's amazing! Was this w/ beta.5 or some other version from last week?

**Comment by matthewnessworthy** [comment]
@toranb with the latest beta 5 from master

**Comment by toranb** [comment]
@matthewnessworthy awesome news! that is the primary RC for the first v4.0.0 (stable) release so great news! I'll look more into the memory leak issue mentioned above before I release it but it's good to know what we have now is solid!

Thanks again for all the testing/feedback/work you put in to get us this far!

**Comment by matthewnessworthy** [comment]
It was my pleasure! Thanks for doing all the work ;)

**Comment by toranb** [comment]
@matthewnessworthy I learned a ton and wouldn't have been successful w/out help from 2 very performance minded folks in the ember community (Erik Bryn and Chris Thoburn).

Just glad to see that for the most part this library is still simple to use/ easy to build relationships with/etc

**Comment by toranb** [comment]
@matthewnessworthy the docs need a massive upgrade before the v4.0.0 final release so I'll need to look that over next week. If you have any input on that or anything else let me know. One part I want to rework completely is the relationship comments made as I've learned a lot in the last year about how to do m2m/ one-to-many with this library and it's not reflected in the documentation now.

**Comment by jasonmit** [comment]
> One part I want to rework completely is the relationship comments made as I've learned a lot in the last year about how to do m2m/ one-to-many with this library and it's not reflected in the documentation now.

This is exciting, we're about to start porting an ED implementation to simple-store and this is the only challenge when I started to scope it all out.

Thanks for this great addon :+1:

**Comment by toranb** [comment]
@jasonmit @matthewnessworthy I've added an unsubscribe api that allows you to remove filtered Arrays (that are returned when you use find w/ a filter of any kind). This removes the memory leak mentioned above but the downside is that it's manual (in the tests below you can see I added a willTransition hook to my route to remove the filters setup in my model hook)

https://github.com/toranb/ember-cli-simple-store/commit/567d4b3436182f377c6966a25928e71d1f400f37

I haven't yet published this as beta.7 but I'm curious what you think -the big acceptance test I added shows the problem by example if you are unfamiliar w/ the issue.

At this time it looks like ember-data has this same memory leak and providing a way to "cleanup" after yourself easily is the least we could do if we take this to v4.0.0 stable later this month.

**Comment by jasonmit** [comment]
Just some bike shedding, but what if instead of keeping these records around and sharing references to it, that query returns a new instance each time it's invoked.  If anyone wants to opt into being notified when a record matching the query is added or removed, they subscribe to an event on the store.  They just also need to be proactive in unsubscribing.

This I think would eliminate the issue (if I am understanding the core issue correctly).

**Comment by toranb** [comment]
@jasonmit if this is something you have some time to spike out I'd love another set of eyes to prove this is possible w/out a huge departure from what the store looks like today. To this point I've spent time working with a performance benchmark to ensure filters run only once during a given run-loop.

I think the challenge with this approach (if I was to implement it myself) is that right now we don't invoke that function more than once. The returned value is an ArrayProxy that we observe changes with to get "the good parts" of 2WDB.

I've starting using another library (redux) recently that acts more like the event based approach you mention but I have a feeling this would be a big shift for ember developers (something I'm considering heavily as I look at 1 way data flow conceptually /what it means for those heavily invested in ember-data/and 2WDB libraries like this one).

To start, how would the event based approach work for my most common filter scenario (shown below)

**the typical one-to-many with user and role**

first we wire up a computed in the user model that will get an array proxy we can filter with. This filter also needs to "re-fire" when a model is added/ or updated via push (the public api of the store to add or update objects)

``` js
export default Model.extend({
    name: attr(),
    store: inject('main'),
    role: Ember.computed.alias('belongs_to.firstObject'),
    belongs_to: Ember.computed(function() {
        const user_id = this.get('id');
        const store = this.get('store');
        const filter = function(role) {
            const users = role.get('users');
            return Ember.$.inArray(user_id, users) > -1;
        };
        return store.find('role', filter);
    })
});
```

a unit test to show this in action would look something like this

``` js
test('role returns associated model or undefined', function(assert) {
    let user = store.push('user', {id: 1});
    store.push('role', {id: 2, name: 'Admin', users: [1]});
    let role = user.get('role');
    assert.equal(role.get('id'), 2);
    store.push('role', {id: 2, users: []}); // requires ember.run in v4.0.0
    role = user.get('role');
    assert.equal(role, undefined);
});
```

**Comment by toranb** [comment]
@jasonmit after some additional thought I think it's worth sharing the real goal of the v4.0.0 release. But first a story :)

Back in the 3.x series I felt this library was "done" in the sense that every feature I needed day-to-day was present and bug free. The downside arrived when I learned of the harm something like a `@each` would do to a computed property in this library. The performance wasn't acceptable but as I started the rework required it was clear the store was suddenly "less" simple.

I understood the tradeoff but quickly found myself hating the api as every piece of production code doing "push" now required an ember.run to flush the queue for relationships to sync up as they did in 3.x. My fear with a large "re-think" is that this library suddenly isn't what I set out to create from the very beginning.

To your point about "subscribe" and "unsubscribe" => I still think it's close to the original use of simple store (w/ the added pain of ember.run all over). When you use a find w/ filter you are in a sense subscribing to changes (the ember 1.x way of thinking). Then later if you want to transition away you can simply unsubscribe to changes (the pain being that it's manual like objective-c all over again).

The problem I solved in the last few weeks was that if we could wait until the end of the run-loop to update each ArrayProxy we could still achieve the simple find/push like api but also the performance that's required to use this with a ton of objects in the store. The big failure on my part was the original implementation used.

1) I start by creating the ArrayProxy requested
2) I then add this proxy to a map in the store so we can look it up later
3) at the end of the run-loop I ask what types need an update (looking at what types have been pushed)
4) I then re-calculate the ArrayProxy content and set it (so this only occurs once instead of X times)

If it's possible to "set the content" using the ArrayProxy itself at the end of the run-loop this would completely eliminate this memory leak issue. I honestly should have spent more time investigating if this was possible and how it would work :)

Do you have any ideas about how we could do something like this or something similar that wouldn't require us holding a separate cache of "filters" to update later (the core problem in this case)?

**Comment by toranb** [comment]
@jasonmit one crazy thought off the top of my head

1) for filtered records we return a subclass of ArrayProxy we own*
2) in the scheduleOnce we ask this SimpleArrayProxy object to update itself
3) inside the new "updateYourself" method we ask if this type has been updated, if so set the content

*one entry point right now so this shouldn't be terribly painful to spike out

If we are able to get the same perf results w/ this we've completely eliminated the memory leak issue and kept the api "simple store" like (ember 1.x thinking about 2WDB /etc).

Is this a crazy /terrible idea to try out or ?

**Comment by toranb** [comment]
@jasonmit looks like a quick run at this wasn't terrible until I hit the "hard part". I need a way to call the "refresh" on each instance (object) from the parent (factory/prototype definition). First up -this is crazy /not sure it can be done but it was a fun take on the memory leak issue we face today.

Any way you can think to make this work from reopenClass ?

``` js
var SimpleStoreArrayProxy = Ember.ArrayProxy.extend({
}).reopenClass({
    refreshContent: function(z) {
        //how to invoke the instance of this on each proxy?
    }
});
```

**Comment by jasonmit** [comment]
> I need a way to call the "refresh" on each instance (object) from the parent (factory/prototype definition).

I'm lacking some context so I don't fully understand the problem being solved.

Whats the idea behind the method hanging off the constructor and what is the `z` argument?  Would it take an instance of `SimpleStoreArrayProxy` and return a new one?

> in the scheduleOnce we ask this SimpleArrayProxy object to update itself

How will the instances be notified that a change took place?  Is the idea that internally, we don't hold reference to the ArrayProxies within the store?  Instead, they subscribe to changes in the store and we let them know when the underlying type changed?  When that event triggers, they reinvoke the query/filter?

I'll spend some time tonight looking at the Store changes on v4 more closely.

**Comment by toranb** [comment]
You can ignore my crazy spike - I think your view of the ArrayProxy fix is the most important priority from my view. Would you have time to take a stab at the solution you proposed (or at the very least how that relationship would look in your view)?

**Comment by jasonmit** [comment]
@toranb yeah I can take a shot at it once I fully grok everything

**Comment by toranb** [comment]
@jasonmit awesome - really appreciate the second look. Sorry to dump 2 years of history on you :)

**Comment by toranb** [comment]
@jasonmit just a heads up - I removed unsubscribe in favor of destroy (about to publish a new beta and didn't want to increase the api surface unless absolutely necessary)

https://github.com/toranb/ember-cli-simple-store/commit/d1eeeb62f628b70d7a396178df6beb293809087c

**Comment by toranb** [comment]
@jasonmit @matthewnessworthy I just released beta 7 (now the destroy method is available on any filtered ArrayProxy so you can remove it if you find the memory leak discovered above problematic at scale).

I just updated the perf app and it looks like the performance of what we have on master now is still rock solid in the example @matthewnessworthy threw together :)

If you guys could upgrade to beta 7 and report any issues - I only found 2 failing tests in a client project (I'll need to see if that's a regression here or w/ how the ObjectProxy was used)

![screen shot 2016-01-29 at 2 01 22 pm](https://cloud.githubusercontent.com/assets/147411/12686741/27ad5db6-c691-11e5-8d6b-79f634be3c89.png)

**Comment by toranb** [comment]
@jasonmit any other ideas about how to avoid the memory leak we have today? I believe this is present in ember-data also but I'd love to hear some new ideas before we push the stable v4.0.0

**Comment by jasonmit** [comment]
@toranb the issue I thought was solved, it just requires the user to be conscious of it and to unsubscribe/destroy the live record array.  Short of that, I don't have anything else in mind right now.  Are there any other leaks?

**Comment by toranb** [comment]
@jasonmit the "destory" will help cut down on the leak but it's something developers will need to be aware of I'm sure. At this time I'm thinking of closing this issue (as the performance work was a success) and opening another w/ some targets for the v4.0.0 release

1) add deprecation for the 3rd param of the public find api (to make it clear this argument is not used)
2) upgrade each example project referenced in the readme
3) mention destroy and why it's useful now in v4.0
4) rewrite the relationship section of the readme to show a one-to-many/m2m example
5) any other misc readme /documentation updates

Anything else you can think of?

**Comment by jasonmit** [comment]
Have you explored implementing a weakmap?  I'm just unsure how references will be freed up within ember.  For example, the models usually stay referenced on inactive controllers/routes.

**Comment by toranb** [comment]
@jasonmit what would a weakmap look like exactly? 

With ember 2.0 (components) you often have the route fetching data for active routes but in a parent/child scenario any cleanup that you kick off in willTransition would occur when you "transition" from parent to child (even when that child route and parent are both in view). It becomes even more difficult if we want to maintain support for ember 1.13 because controllers are singletons that never get thrown out (so far as I know anyway).

After reading this RFC from ember-data it seems clear that we don't have any easy out for this issue. I think at this time we can let the app using simple-store decide when it's done w/ a given array and if they want to call "destroy" it will allow them to reclaim memory.

https://github.com/emberjs/rfcs/pull/23

**Comment by jasonmit** [comment]
> @jasonmit what would a weakmap look like exactly?

Unsure, when I went to implement it I realized we need to enumerate over the filterMaps which wouldn't work with the pattern I was trying for.  Another alternative would be a mixin factory, where we return an Ember.Mixin and hook into the destroy method of the object to release all of the associated record arrays.

The public API would look something like:

``` js
import Ember from 'ember';
import hbs from 'htmlbars-inline-precompile';
import { filter, FilterBuilder } from 'ember-cli-simple-store/find';

let FindThings = FilterBuilder({
  // filter is a cp that returns a record array proxy
  bars: filter('bars'),
  foos: filter('foos', function() {
    return {
      account_id: this.get('model.account_id')
    };
  })
});

export class Ember.Component.extend(FindThings, {
  layout: hbs`
    {{#each foos as |foo|}}
      <strong class="foo">
        {{foo.name}}
      </strong>
    {{/each}}
  `
});
```

No manual releasing required by the users in this example, but the drawbacks in some extra typing..

**Comment by toranb** [comment]
Thanks for the feedback / example. I think the part I'm not in love with...  now your component needs to `mixin` another object responsible for fetching the array data. In my daily work I never have components fetch data like this (it's almost always the route) so it feels strange to see that personally.

It's also possible that we could leave this implementation detail up to the consumer (as this addon is much smaller in scope and often avoids boiling the ocean) -so if they do decide to "fetch data" from a component (and not the route) they can decide to add a mixin/or cleanup in a way that works for them. If instead a dev (like me) would fetch data in the route, they could implement a route mixin (for willTransition lets say).

At this time I think we ship v4.0.0 stable and just make it clear in the docs that a memory leak does exist when you use the "filters" overload for find and how you can manage this w/ destroy. Thoughts ?

**Comment by jasonmit** [comment]
Agreed, lets just stick with what we have and continue to think about the issue.  Maybe some collaboration with the ember-data guys since we all seem to be solving the same thing. :+1:
