### ISSUE TITLE
[feature] Push model to store

### ISSUE THREAD

**Issue by matthewnessworthy** [toranb/ember-cli-simple-store#28]
It would be nice to be able to push a model to a store, currently you can only push the underlaying data.

Primary usage would be when creating a new record while relying on model functionality (validation, relations, CPs, etc)

**Comment by matthewnessworthy** [comment]
I realised after creating this ticket that I am prone to bouts of idiocy, also, I've already solved this by pushing the api response data to the store and transitioning to the new record.

**Comment by toranb** [comment]
haha not to worry - the first iteration of this addon was much like that :)
