### ISSUE TITLE
Make models optional

### ISSUE THREAD

**Issue by bobbysciacchitano** [toranb/ember-cli-simple-store#29]
Hi ... I'm trying out simple-store as a client store for a basic project and reading through the docs it took me a while to realise that you needed to create a model object for each resource you want to store.

Given there's some useful boilerplate functionality in the model object, I was wondering if it would be possible to create a default magic model without having to register models?

**Comment by toranb** [comment]
Rather than a direct answer I decided to reply with an explanation of how those model files are used. In the store we "tag" or associate each model by type. That type is then used by the ember resolver to "build" or "construct" each instance (as you push). Without this I'm not sure it would be clear how each model is silo'd correctly. Most people using this need to silo by type first, then by primary key (id on the model itself).

If adding a "model" from this library is the issue, it's worth mentioning that a simple ember object will work just fine. We have a handful of models that look like this 

``` js
export default Ember.Object.extend();
```

**Comment by bobbysciacchitano** [comment]
Yep no worries! Thanks for the clarification. As an aside my application uses web sockets with a base data set loaded via Ajax at boot which means the store doesn't have any async relationships since the store is always up to date.

One of my biggest pain points is trying to map relationships when they come in via the socket. Would it be possible to extend the base model to get access to the store or make the store injectible? Projects like simple-auth and ember-ajax seem to use this pattern.

Aside from that I think I've become more efficient since switching from ember data.

**Comment by toranb** [comment]
Injection is totally a requirement for bigger apps :)

Here is a short example to inject a status (a one-to-many relationship).

``` js
var Issue = Model.extend({
    store: inject('main'),
    status: Ember.computed.alias('belongs_to.firstObject'),
    belongs_to: Ember.computed(function() {
        let issue_id = this.get('id');
        let store = this.get('store');
        let filter = function(status) {
            let issues = status.get('issues');
            return Ember.$.inArray(issue_id, issues) > -1;
        };
        return store.find('status', filter, ['issues']);
    })
})
```

Here is what the simple inject helper looks like 

https://github.com/toranb/ember-2-skeleton-app/blob/master/app/utilities/store.js

**Comment by bobbysciacchitano** [comment]
I ended up achieving a similar result by overwriting the initialiser and making the store a service. This means I can access the store via `this.get('store')` or `this.store` in the case of routes and controllers. Probably worth mentioning that if you register `service:main` as a separate item, you end up with a new store instance. Took a while to work out what was going on!

```
import Store from '../store';

export default function() {
    var application = arguments[1] || arguments[0];
    application.register('service:store', Store);
    application.inject('controller', 'store', 'service:store');
    application.inject('route', 'store', 'service:store');
}
```

Now more of my boilerplate mapping exists in the model class which is the best outcome.

```
import Ember from 'ember';

export default Ember.Object.extend({

    ajax:  Ember.inject.service(),

    store: Ember.inject.service(),

    save: function() {
        let store = this.get('store');
        let ajax  = this.get('ajax');

        let properties = this.getProperties('id', 'name', 'surname', 'email', 'role', 'access_level', 'status_message');

        properties.status   = this.get('status.id');
        properties.team     = this.get('team.id');
        properties.location = this.get('location.id');

        return ajax.put(`/staff/${properties.id}`, { contentType: 'application/json; charset=utf-8', data: JSON.stringify(properties) }).then((staff) => {
            store.push('staff', staff);
            this.parseRelationships();
        });
    },

    parseRelationships: function() {
        let store = this.get('store');

        if (this.get('status')) {
            this.set('status', store.find('status', this.get('status')));
        }

        if (this.get('team')) {
            this.set('team', store.find('teams', this.get('team')));
        }

        if (this.get('location')) {
            this.set('location', store.find('locations', this.get('location')));
        }
    }

});
```
