### ISSUE TITLE
Use a key name other than 'id'

### ISSUE THREAD

**Issue by salzhrani** [toranb/ember-cli-simple-store#3]
Is there a way to use a property name other than `id` as the identifier ?

**Comment by toranb** [comment]
Today this isn't (yet) an option. Just looking over the store I see about 3 references to id as the identifier

https://github.com/toranb/ember-cli-simple-store/blob/master/addon/store.js#L10
https://github.com/toranb/ember-cli-simple-store/blob/master/addon/store.js#L43
https://github.com/toranb/ember-cli-simple-store/blob/master/addon/store.js#L54

The biggest issue w/ making this configurable is that typically it's something you look for at the model level. When this project was started I tried not to make the special "model" base class a requirement but over time it's become difficult to keep them isolated completely. 

At this point we _could_ look to see what ember-data does to solve this (so the public api remains similar for users who switch between ED and non-ED projects). Would you be up to provide some basic research / propose the changes (conceptually) here to support both id and non id PKs ?

**Comment by salzhrani** [comment]
It seems in ED this customization is done at the [serialzer](https://github.com/emberjs/data/blob/v1.0.0-beta.16/packages/ember-data/lib/serializers/json-serializer.js#L25). conceptually the user can set the `id` property before calling `push` or `remove`, or maybe we can add an optional `primaryKey` parameter to `push` and `remove` which if exists the store will set the proper `id`

```
push: function(type, data, primaryKey) {
    if (primaryKey) {
        data.id = data[primaryKey];
        delete data[primaryKey];
    }
    ...
}
```

**Comment by toranb** [comment]
Not ignoring your request :) just had some BIG changes to the public api WIP and wanted to get those solid/proven before attempting to add support for this.

I do like your feedback btw - give me a week to test the new 0.8.2 series and verify the project is stable

**Comment by toranb** [comment]
Also- would you mind sending my personal gmail a note quick? I'd like to chat offline about how you got here/why (assuming that's cool with you) 

toranb at gmail

**Comment by toranb** [comment]
Finally getting around to implementing this :) and I'm curious if you are actively using this / or plan to once this feature drops. I ask because I don't currently have non-id based pks and being someone who doesn't use this day-to-day makes me think we should get someone like yourself involved /on the core team to help prove the api is what you prefer / adds enough value to use it on your client projects /etc

If we modify the push as you suggested above it has the added benefit of keeping the models configuration free (something I very much like myself). Would you be up to review a PR I throw together for the 1.0 beta channel ? Or do you need this in the 0.9 series ?

**Comment by toranb** [comment]
I'm thinking of making this a 1.1 feature (not pushing it back to the 0.9 series). I'm making a big push tonight to complete the 1.0 and publish it (and I'd like to get some input from you before trying to crank this out myself -as I won't be using the feature myself any time soon).

Thanks for the input - hope 1.1 is acceptable :)

**Comment by toranb** [comment]
Closing this out for now until someone decides to champion it :)
