### ISSUE TITLE
Check out of findOne

### ISSUE THREAD

**Issue by antulik** [toranb/ember-cli-simple-store#30]
I'm doing simple catching when I want to check store before doing ajax request. 

How do I check if `findOne` returns something or nothing. Currently as I can see it always returns an `ObjectProxy` for empty object, but how do I check if it is valid?

I think i can do `store.findOne('user').get('source.length')` but that looks too complicated

**Comment by matthewnessworthy** [comment]
you could do `store.findOne('user').get('firstObject')`

**Comment by toranb** [comment]
@antulik great find - the issue w/ the ObjectProxy is that it's never falsy :(

I've done either what @matthewnessworthy mentioned or this in my repository like classes to check if the object is cached

``` js
  var user = store.findOne('user');
  if(user.get('id')) {
    //this would prove the object has an id (something ObjectProxy doesn't have by default)
  }
```

**Comment by antulik** [comment]
Thanks, that works for me.
