### ISSUE TITLE
Nested model

### ISSUE THREAD

**Issue by antulik** [toranb/ember-cli-simple-store#31]
I have a nested model (it's not a relationship) for example 

``` js
export default Model.extend({
  id: attr(),
  name: attr(),
  extra: attr()
})
```

`extra` is a nested object without `id` field. What do I need to do so `extra` field would be converted to model as well? Right now it stays as plain Object.

**Comment by toranb** [comment]
@antulik I'm not sure anything is built up to support that from the simple store perspective. Usually if I'm nesting I just wire up a simple FK of some kind and "point to" the nested object. If you truly want an ember object to return when you ask for extra you could wire up a simple computed to return another model object (something similar exists in this test route model).

https://github.com/toranb/ember-cli-simple-store/blob/master/tests/dummy/app/models/user.js#L8-L17

It's a normal belongs to like relationship but you could do something similar to get the nested model via some computed property.

**Comment by williamsbdev** [comment]
@antulik Additionally, since you said that nested object does not have an `id`, you will need to supply one on the client side for storing the object in the simple store. Otherwise, the last object of that type pushed into the store will be the only one there (with an id defaulted to `undefined`).

**Comment by antulik** [comment]
so far i've done a work around

``` js
var Extra = Model.extend({
  notification_type: attr(),
});

export default Model.extend({
  id: attr(),
  name: attr(),
  extra: Ember.computed({
    set(key, value) {
      return Extra.create(value);
    }
  }),
});
```

this is not ideal as I still have to remember that parent and child models are not connected. Would be nice if `parent.extraIsDirty` would delegate to `parent.extra.isDirty`, so `parent.isDirty` would work correctly. Same for `save` and `reset`

**Comment by toranb** [comment]
@antulik most of our models have a custom computed that is separate from isDirty so we can ask "is any related /or nested model dirty". I found having this live on a different computed was a good idea as most of the time I want to know if my local attrs are dirty, or if a related attr/model is dirty.

I believe ember-data made this change earlier this year also
