### ISSUE TITLE
Adopt Ember.Service for the store Object

### ISSUE THREAD

**Issue by jasonmit** [toranb/ember-cli-simple-store#34]
The discussion spawned from: https://github.com/toranb/ember-cli-simple-store/pull/32#issuecomment-171785799

Since we're dealing with a singleton Object and ember-data has moved in the `Ember.Service` direction, it would be great if we can adopt a similar API for help adopters transition more easily with a familiar API.  This also will allow consumers to have ember-cli-simple-store work with ember-data in parallel since they will not both be registering under the name `store:main`

**Comment by jasonmit** [comment]
@toranb do you want this in v4 or v5?

**Comment by toranb** [comment]
We can shoot for v4.1

**Comment by jasonmit** [comment]
@toranb okay I opened a PR.  Let me know if you want to make it in sooner, for now I'll be pointing the app I'm working on to that as my working branch.

**Comment by toranb** [comment]
@jasonmit if you need this in your app lets just make it happen as v4 now - go ahead and merge to master if that's cool. If you can use it in your app /provide feedback to get this right before a stable v4.0.0 release is published all the better
