### ISSUE TITLE
Consider better compatability with ember-data

### ISSUE THREAD

**Issue by jasonmit** [toranb/ember-cli-simple-store#45]
I would like to eliminate any pain of having consumers bringing in ember-cli-simple-store into their apps when they have ember-data as a dep.  This spawned from https://github.com/toranb/ember-cli-simple-store/pull/44#issuecomment-172743211

I propose two ideas, either will make this possible.
- [x] We remove the auto-inject initializer altogether and consumers can rely on `Ember.inject.service` in the objects that need to access the store.
- [ ] We agree on renaming `store` to `simpleStore` as the property key for the default initializer.  https://github.com/toranb/ember-cli-simple-store/blob/master/app/initializers/ember-cli-simple-store.js#L12-L13

Would become:

```
app.inject('controller', 'simpleStore', 'service:simple-store');
app.inject('route', 'simpleStore', 'service:simple-store');
```

/cc @toranb @williamsbdev

**Comment by toranb** [comment]
@jasonmit I'm on board w/ this and think you've landed it in the above PR right?

**Comment by jasonmit** [comment]
@toranb I haven't landed it since this would be a breaking change from 3.0->4.0 so help off to gather your feedback.  Which approach do you want me to go with?

**Comment by toranb** [comment]
I think as of v4.0.0 we should make the "default" using Ember.inject.service (skip all the legacy injection tooling that @williamsbdev and I added before services became the way forward)

**Comment by jasonmit** [comment]
Awesome, completely agree
