### ISSUE TITLE
link the "3.6.0" readme in master for people viewing the repo today?

### ISSUE THREAD

**Issue by toranb** [toranb/ember-cli-simple-store#47]
@jasonmit you mentioned this and I didn't know if you had a fancy github way to achieve this :)

**Comment by jasonmit** [comment]
I don't.  I just make it a nice bold header at the top of the README saying the master doesn't reflect the latest stable API.

**Comment by toranb** [comment]
https://github.com/toranb/ember-cli-simple-store/commit/ee2a211fd2adfff35311af4895fb72b99fe902fb

done :)

**Comment by jasonmit** [comment]
:+1:
