### ISSUE TITLE
v4.0.0 upgrade guide

### ISSUE THREAD

**Issue by toranb** [toranb/ember-cli-simple-store#50]
I'm releasing v4.0.0 today and wanted to document some issues I found earlier this year when I did the migration from 3.6.0 => 4.0.0 (beta 7) for a client.
## The store is now a service

Now if you want to use the store you just inject a service like you would traditionally with ember. Making this the default behavior was a big step forward and as you might imagine it introduced one breaking change to be aware of. In the past routes and controllers had the store injected for you w/ help from an initializer we shipped in previous versions of ember-cli-simple-store. With the v4.0.0 release we no longer wire this up for you so you will need to inject the service yourself at any spot you used the store previously.

``` js
import Ember from "ember";

export default Ember.Route.extend({
    simpleStore: Ember.inject.service()
});
```

If you are a team with a big codebase and don't have time to re-tool everything in one pass, you can add an initializer like you see below and everything will work as it did prior to the upgrade. I used this to upgrade a simple example ember project recently if you prefer to see the [commit](https://github.com/toranb/ember-2-skeleton-app/commit/998708d66d64bbaa6241b08960178f85e7820afa).

``` js
import Store from 'ember-cli-simple-store/store';

export function initialize() {
    var application = arguments[1] || arguments[0];
    application.register('store:main', Store);
    application.inject('controller', 'store', 'store:main');
    application.inject('route', 'store', 'store:main');
}

export default {
    name: 'simple-store',
    initialize: initialize
};
```

If you want to see what it would look like to update a project that previously used the initializer and went all service injected this [commit](https://github.com/toranb/ember-2-skeleton-app/commit/268b97e0e012208c09f26fcc9ae49fd5fa32ccb7) shows it in action.
## The find api takes one less argument

In the previous version we required 3 args for a find w/ filter to run.

1) the type
2) the filter itself (or object literal to be concise)
3) the computed properties that should break the cache on that filter

Because we greatly modified how find works under the hood this 3rd argument isn't required any longer. The library should warn you with a simple deprecation - remove the 3rd argument and this should go away.
## More explicit run loops are required*

In previous versions we didn't think much about the performance implications of push/remove/clear and as a result we ended up with terrible user experiences as the amount of data grew in your application. To be honest, the v4.0.0 release was entirely dedicated to performance so we could provide quick pushes even when the app had a large amount of data in memory.

Some perspective - if you had 4000 records in the store and decided to push 100 at once (in a bulk transaction of some kind) it would take nearly 11 seconds to complete (locking the UI - making your app look unresponsive in the process). With the release of v4.0.0 you can now push those 100 records in around 105ms.

This performance boost didn't come without a tradeoff of course. Now when you push/clear/remove we schedule that action with the ember run loop to ensure we run the filters efficiently. What this means to you (the developer) is that any place you would normally push/clear/remove you will need to ensure it's wrapped in ember.run. The good news ... if you are doing this in a route/closure action or ajax callback it's very possible you already perform the work inside of an ember.run so no real need to change any production code.  

So when will you need to change anything? This ember.run really only came up in 2 situations from my experience

1) testing: if you had push/remove/clear all over in test code it's possible you would need to wrap that w/ ember.run (let a failing unit test tell you this first before you take any action). The good news -if you did find a handful of tests (or an entire suite) I was able to extend the normal test function in `qunit` to wrap the test callback with ember.run (meaning I didn't need to update/touch each unit test that broke).

``` js
var test = function() {
    for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; ++_key) {
        args[_key] = arguments[_key];
    }
    var callback;
    function wrapper() {
        let argz = arguments;
        Ember.run(function() {
            callback.apply(null, argz);
        });
    }
    callback = args.splice(1, 1, wrapper)[0];
    qunitTest.apply(null, args);
};
```

I was able to use this in my first upgrade to v4.0.0-beta.7 and you can see it in the [diff](https://github.com/toranb/ember-2-skeleton-app/commit/998708d66d64bbaa6241b08960178f85e7820afa) here (it fixed a failing test I found during the upgrade).

2) relationships: if you used the store to build rich relationships like one-to-many/m2m and in doing so leveraged the find api w/ a custom filter you may need to wrap that model code in ember.run explicitly. The situation in which a production regression will show up is described below.

a) relationship code runs to add a new m2m join model
b) next line of code executed after that m2m record is added looks to see how many related m2m join models are setup
c) w/out an ember.run you find that the number is 1 off because ... the scheduled push hasn't been added to an explicit ember.run loop (meaning the filter hasn't re-calculated yet)

To fix this simply wrap step A (above) with ember.run and step C should return the correct number of join models as the filter will be executed right away instead of delayed.
## Find with a filter has a cost

In previous versions I found myself using the find api (w/ filter) all over just because it was easy and worked reliably like a traditional filter on `Array` in vanilla JavaScript. With the recent performance work it became clear that this library needed to become much smarter about when to calculate results of a filter. As mentioned above we schedule this to be more efficient but as a result each find (w/ filter) is now held onto and then evaluated at the end of the run loop.

This isn't to say you shouldn't use the find api, but one way to think of the find api in v4.0.0 is that it's most useful when you need an observable array (something that you can change over time/ have the results update an `hbs` template or some model relationship). It shouldn't be used to quickly loop over some array of models and "filter down" for one off calculations. Instead if you need a list of models filtered down once you can do something this instead 

``` js
simpleStore.find('people').toArray().filter(function ...)
```
## The memory leak PSA

As a result of the work mentioned above any find api (w/ filter) creates an observable array that we hold onto and evaluate until the most efficient time during the run loop. One challenge we found implementing this was that we don't know exactly when to cleanup or remove these references. And because we don't want to guess on your behalf these references stick around forever ... unless you explicitly decide to have them removed. 

I'm not a huge fan of explicit memory management and truthfully you may never have the need for it. But because this was a true technical set-back in my view I wanted to allow developers the option to destroy any observable array we hold on to (to reduce the memory footprint over time).

We added a destroy method and show it in action [here](https://github.com/toranb/ember-cli-simple-store/blob/master/tests/dummy/app/routes/filters.js#L43-L49). Imagine you come into a route w/ a big list of users and when you leave that route you'd like to know the observable array isn't floating around in the store taking up space/leaking memory.

In your routes willTransition action you can destroy the array you created in the model hook like so

``` js
import Ember from "ember";

export default Ember.Route.extend({
    simpleStore: Ember.inject.service(),
    model() {
        var simpleStore = this.get("simpleStore");
        var filter = function(m) {
            return Ember.get(m, "size") > 50;
        };
        return simpleStore.find("robot", filter);
    },
    actions: {
        willTransition() {
            var currentModel = this.get("currentModel");
            currentModel.destroy();
        }
    }
});
```

Luckily I'm not alone trying to solve this hard problem! The ember-data team had an [RFC](https://github.com/emberjs/rfcs/pull/23) a while back that truly discusses the challenges and even one solution that didn't get adopted. If you feel passionate about this memory leak issue and want to help out please reach out so we can solve this together :)

**Comment by robclancy** [comment]
Most libraries we use to do with ember (including official) I have been frustrated with and eventually do our own code (or really want to). This however has always just worked and when running into issues was easy to solve. So thanks! :)

**Comment by toranb** [comment]
@robclancy wow that is hands down the best compliment anyone doing OSS could receive! I'm truly humbled! Thank you for the kind words!!!
