### ISSUE TITLE
Example repo that works along side ember-data?

### ISSUE THREAD

**Issue by toranb** [toranb/ember-cli-simple-store#51]
@jasonmit I know you have had success using this along side ember-data but I realized 2 things today as I shipped v4.0.0 (stable) and wrote the upgrade guide.

1) the install instructions still show that you need to remove ember-data from package.json/bower.json

Assuming that's not true ... could we remove that to not scare people off?

2) the examples work and I have a 1.12 example (and a 2.3 [example](https://github.com/toranb/ember-2-skeleton-app) not yet added) but we don't have an example that shows ember-data works with this installed (and vice versa)

Would you have any time this month to build a dead simple app that would serve as an example to prove these can exist together in v4.0.0 no problem?

**Comment by jasonmit** [comment]
Sounds good :+1:

**Comment by jasonmit** [comment]
@toranb updated the documentation.  Nothing is required for consumers to use `ember-data` and `ember-cli-simple-store` in the same project.  They no longer conflict with each other.

**Comment by toranb** [comment]
@jasonmit awesome! Agreed that it's nothing special - mostly I just wanted to see it in action (maybe a situation where they both make sense together if possible?)

**Comment by jasonmit** [comment]
:+1:

**Comment by toranb** [comment]
cool - I also updated the readme to show an ember 2.4 example w/ simple store (as most of the others are 1.12/1.13). I then did a publish to npm so the readme doesn't have all the `rm -rf ember-data` stuff :)

https://www.npmjs.com/package/ember-cli-simple-store

**Comment by toranb** [comment]
closing this as it's been literally months w/ no movement :)
