### ISSUE TITLE
How to get all `attrs` on a model

### ISSUE THREAD

**Issue by aaronlelevier** [toranb/ember-cli-simple-store#52]
Toran,

Is there a simple way to get all `attrs` on a simple store model? Basically, I want to evaluate the model for `attrs` to see if they've been populated, so for the case that the model is clean and has data, vs. clean and has no data.  

So being able to call: `model.attrsAll()` and get back a filtered Ember object for example. Then I plan to check if the value of each `attr` is truthy, so I could put at computed property, like `hasData` or `hasNoData`. 

Thanks

**Comment by snewcomer** [comment]
From model.js where `obj` is the model instance.

```
function attrs(obj) {
    var all = [];
    factory(obj).eachComputedProperty(function (key, meta) {
        if (meta.isAttribute) {
            all.push(key);
        }
    });
    return all;
}
```

**Comment by toranb** [comment]
@aronysidoro You could define a custom computed on your model that represents the aggregate of "all attrs" using the helper @snewcomer mentioned.

I use it in the model today so I can loop over and create a custom "isDirty" attr from it for each attr 

``` js
var model = this;
var attributes = attrs(this);
attributes.forEach((attrName) => {
  defineProperty(model, attrName + "IsDirty", computed(function() {
    //do some work in here
  });
})
```

**Comment by aaronlelevier** [comment]
@snewcomer,

What is `factory` in this code?

``` javascript
function attrs(obj) {
    var all = [];
    factory(obj).eachComputedProperty(function (key, meta) {
        if (meta.isAttribute) {
            all.push(key);
        }
    });
    return all;
}
```

**Comment by snewcomer** [comment]
@aronysidoro:

https://github.com/toranb/ember-cli-simple-store/blob/master/addon/model.js#L13

from:

https://github.com/emberjs/ember.js/blob/ed298ced885b2f4b4435fbccb26b24b9a24bb68f/packages/ember-runtime/lib/system/core_object.js#L640
