### ISSUE TITLE
Question: Store pushes async

### ISSUE THREAD

**Issue by benkiefer** [toranb/ember-cli-simple-store#55]
We are in the process of upgrading to the latest version of simple store, and noticed that all of our tests started failing because of the introduction of a schedule to the push and clear methods of the store.

Any thoughts on making that synchronous in test mode?

**Comment by toranb** [comment]
In the v4 upgrade guide I show a helper that made the upgrade less painful for a client I was working with last year. The push api is async because the v4 release was all about performance /better scheduling.

https://github.com/toranb/ember-cli-simple-store/issues/50
