### ISSUE TITLE
Find with id filter returns type of object, rather than the type property of the object

### ISSUE THREAD

**Issue by benkiefer** [toranb/ember-cli-simple-store#56]
The following test fails due to the filter having a type property that is the type of the object.

```
test("find with filter does not trump type property of object", function(assert) {
  store.push("person", {
    id: 9,
    firstName: "Jarrod",
    lastName: "Taylor",
    type: "developer"
   });
  assert.equal(store.find("person", 9).get("type"), "developer");
});
```

It looks like this is due to the record-proxy having a property called type.

Gut feeling is that we should namespace the properties on this object to avoid possible collisions in the future (ex: source should be recordSource, type should be recordType).

Thoughts?

**Comment by benkiefer** [comment]
Potentially even _recordType and _recordSource or whatever other convention you think is appropriate.

**Comment by toranb** [comment]
@benkiefer good catch - looks like a regression we didn't see previously. Mind writing up a PR for this using the underscore naming you suggest?

**Comment by benkiefer** [comment]
No problem, working on it now

**Comment by benkiefer** [comment]
I did the same thing on the source and store properties as well. Content felt like a breaking change since it's what you use to make sure the thing is actually loaded. Leaving it alone for now.

**Comment by toranb** [comment]
@benkiefer right on - content is a ember proxy thing and would be very painful to switch out
