### ISSUE TITLE
Find with filter and computed keys is not deprecated, it's been removed

### ISSUE THREAD

**Issue by benkiefer** [toranb/ember-cli-simple-store#58]
As part of our upgrade, we noticed that:

```
store.find("person", someFunction, ["name"]);
```

is generating a lot of deprecation warnings. Unfortunately, it's not really deprecated, support for that functionality is gone even though the deprecation warning says that it will be removed in 5.0.0. It looks like it was removed back in commit fe2ab0043eec9b7d58cc3f2ba3bce47abe35f249.

I'm fine with dealing with the removal (provided the warnings are gone), or adding the functionality back in and still receiving the warnings. What do you think?

**Comment by toranb** [comment]
Truthfully I used the deprecation warning to call out a param that could be removed (so people wouldn't need to hunt for that dead argument by hand). The good news is that the store no longer needs this param to re-run the filter function as it did previously.

If you find a bug around this let me know but this change was at the center of the performance work done in v4

**Comment by benkiefer** [comment]
Ok, we're seeing some strangeness in our upgrade process for the old privacy app where it looks like we did a lot of those filters. Will update or open a PR is something comes up.

Thanks again Toran!

**Comment by toranb** [comment]
@benkiefer if you do find something not described in the [v4 upgrade guide](https://github.com/toranb/ember-cli-simple-store/issues/50) I'll gladly take a look
