### ISSUE TITLE
Support for 1.13 && upgrade to remove deprecation _lookupFactory

### ISSUE THREAD

**Issue by snewcomer** [toranb/ember-cli-simple-store#72]
@toranb still looking to support 1.13?  Looking to resolve this as well: 

http://emberjs.com/deprecations/v2.x/#toc_migrating-from-_lookupfactory-to-factoryfor

Commit to fix it:

https://github.com/snewcomer/ember-cli-simple-store/commit/b07e2d6e018f44d21f25db1313ac01dc2eae4d69

**Comment by toranb** [comment]
@snewcomer hmm great question about support. Is it possible to "support" 1.13.13 while not having dep warnings for 2.12 users? If not ... it may be time to drop 1.13.13 support

cc @jasonmit

**Comment by snewcomer** [comment]
yep possible to support w/ the get owner polyfill.  Was just curious.

**Comment by toranb** [comment]
@snewcomer I think if we can support 1.13 just by using this updated polyfill it would go a long way. I know my current employer is still using 1.13.13 and others are likely in the same boat.

Could we close out this issue/look into 2.12/2.13 support at some point in the next few weeks?
