### ISSUE TITLE
factoryFor and injections

### ISSUE THREAD

**Issue by snewcomer** [toranb/ember-cli-simple-store#79]
https://github.com/emberjs/rfcs/blob/master/text/0150-factory-for.md
http://emberjs.com/deprecations/v2.x/#toc_migrating-from-_lookupfactory-to-factoryfor

I'm looking at something like below.  After upgrading our app to ember-source: 2.12, it seems based on the above RFC and the migration from _lookupFactory to a new API for factoryFor, the only way to get injected properties is through `factory.create`.  So in the model below, I will get an error because DI doesn't work since this [line](https://github.com/toranb/ember-cli-simple-store/blob/master/addon/store.js#L21) doesn't allow for `simpleStore` to be resolved later like .

```
// my-app/models/invoice-list.js
export default Ember.Object.extend({
  simpleStore: service(),
  invoice: computed(function() {
    const store = get(this, 'simpleStore');
    return store.find('invoice', get(this, 'id'));
  }).readOnly(),
  isDirtyOrRelatedDirty: computed('invoice.isDirtyOrRelatedDirty', function() {
    return get(this, 'invoice').get('isDirtyOrRelatedDirty');
  }).readOnly(),
  isNotDirtyOrRelatedNotDirty: computed.not('isDirtyOrRelatedDirty'),
});
```

Any thoughts on getting DI to work with simple store objects?

**Comment by snewcomer** [comment]
Curiously, if I set `set(model, 'simpleStore', store)` and pass it through `store.push`, then all is good because when it is passed through `factory.create`, it has the `simpleStore` injected.

**Comment by toranb** [comment]
@snewcomer ah this is an interesting find. Let me carve out some time this weekend to take a serious look -thanks for point it out!

**Comment by snewcomer** [comment]
Thanks Toran.  I think I may have figured something out - my original issue was mis directed and not related to simple store.  This object I referenced above is invoked via `factory.create` on my side, and by setting `simpleStore` on that object before being passed to my `factory.create` function, the object has has its dependencies (mainly simpleStore).  Simple store [here](https://github.com/toranb/ember-cli-simple-store/blob/master/addon/models/record-proxy.js#L19) does a lookup and thus will register with the container, so don't think upgrading past 2.12 is inherently a problem with simple-store.  My bad.

Lmk if I have anything wrong here.
