### ISSUE TITLE
What should the default value be for attr?

### ISSUE THREAD

**Issue by toranb** [toranb/ember-cli-simple-store#8]
In the latest pull request @williamsbdev found that by default an attributes value is undefined. This in itself might not be totally incorrect but because of how we "protect against" the "" (empty string) when you set the value using attr it behaves strange / incorrectly (as shown below)

``` js
test("today if you expect empty string to be a default value you will be sad", function(assert){
    brandon = Person.create({id: 1, firstName: "", lastName: "Williams"});
    assert.equal(undefined, brandon.get("firstName")); // this feels broken
    brandon.set("firstName", "");
    assert.equal(undefined, brandon.get("firstName")); // this also feels broken
    brandon.set("firstName", "baz");
    brandon.set("firstName", "");
    assert.equal("", brandon.get("firstName"));
});
```

This isn't by accident so let me explain why this occurs today so we can find a way to move forward.

When I first wrote attr I wanted to keep the extra "type" information out of scope. For example - instead of attr("string") or attr("number") I just wanted to write attr(). This design decision let me to believe that using "undefined" as the default value was correct (as I knew nothing of the type and didn't care for sake of the model/ dirty tracking/ rollbacks / etc).

Later I started writing a validation library that would take a dependency on the store / model and attr. The attr was used to determine if the "field" was dirty - if yes I would then fire the validation and show the user what the field required to be "valid".

The UX requirements that I cared about are:

1) If you started typing into the field (now dirty) I wanted to show the error. If they backspaced out I still wanted to show the error as they clearly started typing so it seemed logical to show them what was expected of them.

2) If you open a new (empty) form and just hit tab to jump from one field to the next - you wouldn't see any of the validation errors (ie- the field should not be set as dirty / changed)

The 2nd item above was the reason I protected the "attr" from setting "" (empty string) - it turns out that when you go from undefined to empty string the field and model is now dirty (showing the validation error). *\* problem for ux

To fix this issue I default all attr values to "" (empty string) so when the user "tabs through" a form it will only "set" each to the already default value of "" (empty string). And because it's the same the field won't be dirty -so it won't fire the validation :)

The downside of this "fix" was that if you start typing (error shows up) - and you then backspace (to nothing) the value of the attr is back to the original /default value "" (empty string) so ... it's no longer dirty (hiding the validation error we said should be showing at this point) **jsbin to show how this is broken

http://jsbin.com/cebuziquji/1/

Solving this requires 2 changes that are worth talking about in this thread

1) should we make "" (empty string) the default value for attr or should it remain undefined. Thinking about non input model fields (like checkbox / radio button / selectbox) this seems like it might not be correct ... unsure so I'm open to the discussion

2) if we make "" (empty string) the default - the validation library will need to use another field to determine if it's time to "show errors". Instead of isDirty (at the field level) I think I could just as easily use something like "isPrimed" at the field level to alert the validation component that "yes they've starting using this field so it's safe to show stuff" (though even this computed will need a special "protection" to stop isPrimed from being true when "only" empty string is the value being set on the models attr) - again the user should be able to tab through a form without firing off the world **part of the ux requirement

Whatever we decide I'm planning to leave the 0.9 series as is (using undefined) because this will likely be a breaking api change for people using the library today. The 1.0 (and 1.0 betas) will use this new "default attr value" when we determine what it should be.

**Comment by toranb** [comment]
After talking w/ @williamsbdev today it's clear that a default value of "undefined" is the best option today. The (small) change required to fix the "setter" of empty string will be available in both the 0.9 and 1.0 series as it's non breaking after all.

https://github.com/toranb/ember-cli-simple-store/blob/master/addon/model.js#L37

The line above will change to ...

``` js
var primed = Ember.isNone(value) && !data[key];
```

The issue I'll need to solve before merging that is "how to keep the ux in validation" (once this change is in master). I don't currently have an idea on this but I'm planning to devote the week to solving this.

**Comment by toranb** [comment]
The more I think through this, the more I think it's actually fine the way it is with the caveat that it seems strange to see a unit test that fails to set a value of empty string on a new model.

example:

when you create a new model and you are ready to save it /fire off an xhr. You usually turn the objects properties into json first like so

``` js
import Ember from "ember";
import PromiseMixin from "ember-promise/mixins/promise";

export default Ember.Object.extend({
    save: function(model) {
        var hash = {
            data: JSON.stringify({title: model.get("title")})
        };
        return PromiseMixin.xhr("/api/todos", "POST", hash);
    }
});
```

If your model has a title of empty string it's just the same as not sending it to your backend (as both should fail any validation you have server side). The only thing to be aware of that _might_ cause users pain is if that title property is truly the ONLY value you JSON stringify because "undefined" will return something _fun_

``` js
"{}"
```

I feel confident this isn't a true issue you run up against in production because I hacked our node modules (on a client project) to change this and not a single test failed (meaning if we expected nothing to hit the server / nothing went with either configuration).

Without this change it's easy to leave the default value as undefined. This allows us to support the scenario where you have a radio button w/ int values or a input with string values (without prescribing the default value be a string/or making the user provide more meta data about the type itself).

Also after searching around the web I couldn't find another way to provide the same great UX you get in validation once we alter the behavior I mentioned above. This along w/ the paragraph above leads me to think we should avoid any changes to this for the moment.

Thoughts?

**Comment by williamsbdev** [comment]
When I originally found this, it was only in a unit test. At that point, we had been using this library in our production app for quite some time without issue. I do not feel this is worth addressing at this point as you said if it breaks some desired UX. I have not seen issues related to AJAX requests but will keep this mind in case I do run into trouble.

Thanks!
