### ISSUE TITLE
Issues with Ember >= 3.4.0

### ISSUE THREAD

**Issue by ghost** [toranb/ember-cli-simple-store#90]
I am getting an error of:

```
TypeError: Cannot read property 'eachComputedProperty' of undefined
    at clone (model.js:34)
```
after upgrading my apps which use **ember-cli-simple-store** to ember 3.4.0 and any subsequent version. This seems to be related to changes to `ClassMixin`, but I am not that knowlegeable of Ember internals to know more.

**Comment by toranb** [comment]
@lele-melis great find! I'll see if I can find a work around for apps running >= ember 3.4 this week!

**Comment by toranb** [comment]
@lele-melis  this is now fixed and live on npm as v5.9.4

Any questions or issues let me know! Thanks again for opening this issue!

**Comment by walter** [comment]
#91 may not be a complete fix. I may have tripped over a related problem. Recently upgraded to `3.4.7`.

I find an exception in the `content` property when I inspect an object loaded from the store after a particular transition:

```JavaScript
content: [Exception: TypeError: Cannot read property 'objectAt' of undefined at Class.compute (http://localhost:4200/assets/vendor.js:67659:47) at Class.<anonymous> (http://localhost:4200/assets/vendor.js:67422:25) at ComputedProperty.get (http://localhost:4200/assets/vendor.js:45827:36) at Class.CPGETTER_FUNCTION [as content] (http://localhost:4200/assets/vendor.js:44097:31) at Class.invokeGetter (<anonymous>:2:14)]
```

I call it with `this.get('client.hasAccommodationSupplement')` and the `get` call returns falsey (even though it should return `true` in this context). If I transition away and come back, it returns correct value.

**Comment by walter** [comment]
> I call it with `this.get('client.hasAccommodationSupplement')` and the `get` call returns falsey (even though it should return `true` in this context).

To be more specific, it returns `undefined`.

**Comment by walter** [comment]
> I call it with `this.get('client.hasAccommodationSupplement')` and the `get` call returns falsey (even though it should return `true` in this context).

Whereas `this.get('client').get('hasAccommodationSupplement')` returns `true`. 🤔

**Comment by toranb** [comment]
@walter  could you reproduce this with an example so I can dive in and see what's up? thanks much!

**Comment by walter** [comment]
Welp, tried to reproduce with a stripped down example app and couldn't.

The `client` object in our codebase is a "god" object and is more convoluted than the New York Subway. Pretty hard to extract and have reflect all of its peculiarities. So it could very well be a bug in our code.

I would appreciate a ping if anything does come up in `simple-store` or even `ember` that you think I should know about related to this problem. Thanks for your time!
